AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: app.handler
    MemorySize: 128
    Runtime: python3.6
    Timeout: 3
    Tracing: Active

# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    FunctionName: HelloWorld
    Properties:
      CodeUri: hello_world/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  NotificationFunction:
    Type: AWS::Serverless::Function
    FunctionName: notification
    Properties:
      CodeUri: notification
      Events:
        Callback:
          Type: Api
          Properties:
            Path: /topic/{id}
            Method: get

  SubscribeFunction:
    Type: AWS::Serverless::Function
    FunctionName: subscribe
    Properties:
      CodeUri: subscribe/
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt TopicTable.StreamArn
            BatchSize: 10
            StartingPosition: TRIM_HORIZON

  TopicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn

